name: Gather Release Tags
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  gather-tags:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest final release tag
        run: |
          LAST_FINAL=$(gh release list --exclude-pre-releases --limit 1 --json tagName --jq '.[0].tagName')
          echo "LAST_FINAL=$LAST_FINAL" >> $GITHUB_ENV

      - name: Get first tag after last final release
        run: |
          FIRST_TAG=$(git tag --sort=version:refname \
            | awk -v last="$LAST_FINAL" 'found{print; exit} $0==last{found=1}')
          echo "FIRST_TAG=$FIRST_TAG" >> $GITHUB_ENV

      - name: Get latest prerelease tag
        run: |
          LATEST_RC=$(gh release list --json tagName,prerelease \
            --jq '.[] | select(.prerelease) | .tagName' | head -n1)
          echo "LATEST_RC=$LATEST_RC" >> $GITHUB_ENV

      - name: Collect tags between FIRST and LATEST_RC
        run: |
          TAGS=$(git tag --sort=version:refname \
            | awk -v start="$FIRST_TAG" -v end="$LATEST_RC" '
                found && $0==end { print; exit }
                found           { print }
                $0==start       { found=1 }
              ')
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Debug values
        run: |
          echo "LAST_FINAL=$LAST_FINAL"
          echo "FIRST_TAG=$FIRST_TAG"
          echo "LATEST_RC=$LATEST_RC"
          echo "TAGS=$TAGS"

      - name: Update prerelease notes
        run: gh release edit "$LATEST_RC" --notes "## Included tags:\n$TAGS"
