name: Gather Release Tags
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  gather-tags:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest final release tag
        run: |
          LAST_FINAL=$(gh release list --exclude-pre-releases --limit 1 --json tagName --jq '.[0].tagName')
          echo "LAST_FINAL=$LAST_FINAL" >> $GITHUB_ENV

      - name: Get first tag after last final release
        run: |
          FIRST_TAG=$(git tag --sort=version:refname \
            | awk -v last="$LAST_FINAL" 'found{print; exit} $0==last{found=1}')
          echo "FIRST_TAG=$FIRST_TAG" >> $GITHUB_ENV

      - name: Get latest prerelease tag by date
        run: |
          LATEST_RC=$(
            gh api /repos/${{ github.repository }}/releases \
              --jq 'map(select(.prerelease)) | sort_by(.created_at) | reverse | .[0].tag_name'
          )
          echo "LATEST_RC=$LATEST_RC" >> $GITHUB_ENV

      - name: Collect tags between FIRST_TAG and LATEST_RC
        run: |
          TAGS=$(git tag --sort=version:refname | awk -v start="$FIRST_TAG" -v end="$LATEST_RC" '
            $0==start { print; if (start==end) exit; found=1; next }
            found && $0==end { print; exit }
            found { print }
          ')
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Update prerelease notes
        run: gh release edit "$LATEST_RC" --notes "## Included tags:\n$TAGS"
