# This workflow collects all tags between the last final release and the latest prerelease
name: Get Release Tags
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest final release tag
        run: echo "LAST_FINAL=$(gh release list --exclude-prerelease --limit 1 --json tagName --jq '.[0].tagName')" >> $GITHUB_ENV

      - name: Get first tag after last final release
        run: |
          FIRST=$(git tag --sort=version:refname | awk -v last="${{ env.LAST_FINAL }}" 'found{print; exit} $0==last{found=1}')
          echo "FIRST_TAG=$FIRST" >> $GITHUB_ENV

      - name: Get latest prerelease tag
        run: echo "LATEST_RC=$(gh release list --prerelease --limit 1 --json tagName --jq '.[0].tagName')" >> $GITHUB_ENV

      - name: Collect tags between FIRST and LATEST_RC
        run: |
          TAGS=$(git tag --sort=version:refname \
            | awk -v start="$FIRST_TAG" -v end="$LATEST_RC" '
                found && $0==end { print; exit }
                found           { print }
                $0==start       { found=1 }
              ')
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Update prerelease notes
        run: gh release edit "${{ env.LATEST_RC }}" --notes "## Included tags:\n${{ env.TAGS }}"
