# .github/workflows/package-and-install.yml
name: Package and Install
on:
  workflow_run:
    workflows: ["Gather Release Tags"]
    types: [completed]

permissions:
  contents: write

jobs:
  package-and-install:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: staging
    runs-on: ubuntu-latest
    env:
      DEVHUB_AUTH_URL: ${{ secrets.DEVHUB_AUTH_URL }}
      SF_ORG_AUTH_URL: ${{ secrets.SF_ORG_URL }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ORG_ALIAS: ${{ github.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up sf CLI
        uses: patrykacc/sf-cli-setup@v1.1.0
        with:
          version: latest

      - name: Authenticate to Dev Hub
        run: |
          echo "$DEVHUB_AUTH_URL" > devhub.authurl
          sf org login sfdx-url -f devhub.authurl -a DevHub --set-default-dev-hub
          rm devhub.authurl

      - name: Authenticate to Environment Org
        run: |
          echo "$SF_ORG_AUTH_URL" > org.authurl
          sf org login sfdx-url -f org.authurl -a $ORG_ALIAS --set-default
          rm org.authurl

      - name: Get latest prerelease tag
        id: get-rc
        run: |
          LATEST_RC=$(gh api /repos/${{ github.repository }}/releases \
            --jq 'map(select(.prerelease))|sort_by(.created_at)|reverse|.[0].tag_name')
          echo "LATEST_RC=$LATEST_RC" >> $GITHUB_ENV

      - name: Create beta package version
        id: pkg
        run: |
          echo "Latest RC tag: $LATEST_RC"
          VERSION_ID=$(sf package version create \
            --package MyPackage@${LATEST_RC} \
            --installationkeybypass --wait 10 --json \
            | jq -r .result.Id)
          echo "VERSION_ID=$VERSION_ID" >> $GITHUB_ENV

      - name: Promote package version
        if: env.VERSION_ID && env.VERSION_ID != 'null'
        run: |
          sf package version promote \
            --package-version-id $VERSION_ID \
            --noprompt

      - name: Install package into target org
        run: |
          sf package install \
            --package $VERSION_ID \
            --target-org $ORG_ALIAS \
            --wait 10

      - name: Run Apex tests
        run: |
          sf apex run test --target-org $ORG_ALIAS
