# .github/workflows/prod-deploy.yml
name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sfdx-actions/setup-sfdx@v1
      - name: Authenticate to Production Org
        run: |
          echo "${{ secrets.SFDX_PRODUCTION_URL }}" > prod.txt
          sf org login sfdx-url -f prod.txt -a production --set-default
          rm prod.txt
      - name: Install latest package
        run: |
          sf package install \
            --package latest \
            --targetusername production \
            --wait 20 \
            --publishwait 10
