name: CICD Delta Change Detection 

on: 
  workflow_dispatch: 
    inputs: 
      environment: 
        description: Select the target org 
        required: true 
        type: choice 
        options: 
          - ToCpq 
          - bar 
          - baz 

jobs: 
  build: 
    runs-on: ubuntu-latest 
    
    steps: 
      - name: Check out repository 
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0 

      - name: Set up Node 
        uses: actions/setup-node@v4
        with: 
          node-version: "18" # Updated to a more recent Node version

      - name: Set up SF CLI 
        run: |
          npm install -g @salesforce/cli
          sf plugins install sfdx-git-delta --confirm

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_INTEGRATION_URL }}" > ./SFDX_AUTH_URL.txt
          sf org login sfdx-url -f ./SFDX_AUTH_URL.txt -a integration
        
      - name: Generate delta 
        run: | 
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*' 
          git fetch --all 
          mkdir -p .sgd-output 
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output-dir .sgd-output 
          cat .sgd-output/package/package.xml  

      - name: Map environment to org alias
        id: org-mapping
        run: |
          case "${{ github.event.inputs.environment }}" in
            "ToCpq") echo "target_org=ToCpq" >> $GITHUB_OUTPUT ;;
            "bar") echo "target_org=barOrg" >> $GITHUB_OUTPUT ;;
            "baz") echo "target_org=bazOrg" >> $GITHUB_OUTPUT ;;
            *) echo "Unknown environment" && exit 1 ;;
          esac

      - name: Deploy delta 
        run: | 
          sf project deploy preview \
            --manifest .sgd-output/package/package.xml \
            --post-destructive-changes .sgd-output/destructiveChanges/destructiveChanges.xml \
            --target-org ${{ steps.org-mapping.outputs.target_org }}
          
          sf project deploy start \
            --manifest .sgd-output/package/package.xml \
            --post-destructive-changes .sgd-output/destructiveChanges/destructiveChanges.xml \
            --target-org ${{ steps.org-mapping.outputs.target_org }}
