name: CICD Delta Change Detection 

on: 
  workflow_dispatch: 
    inputs: 
      environment: 
        description: Select the target org 
        required: true 
        type: choice 
        options: 
          - ToCpq 
          - bar 
          - baz 

jobs: 
  build: 
    runs-on: ubuntu-latest 
    
    steps: 
      - name: Check out repository 
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0 

      - name: Set up Node 
        uses: actions/setup-node@v4
        with: 
          node-version: "18"

      - name: Set up SF CLI and plugins
        run: |
          npm install -g @salesforce/cli
          echo 'y' | sf plugins install sfdx-git-delta

      - name: Get secrets based on environment
        id: get-secrets
        run: |
          case "${{ github.event.inputs.environment }}" in
            "ToCpq") echo "auth_url=${{ secrets.TOCPQ_AUTH_URL }}" >> $GITHUB_OUTPUT ;;
            "bar") echo "auth_url=${{ secrets.BAR_AUTH_URL }}" >> $GITHUB_OUTPUT ;;
            "baz") echo "auth_url=${{ secrets.BAZ_AUTH_URL }}" >> $GITHUB_OUTPUT ;;
            *) echo "Unknown environment" && exit 1 ;;
          esac

      - name: Authenticate to Salesforce
        run: |
          echo "${{ steps.get-secrets.outputs.auth_url }}" > ./SFDX_AUTH_URL.txt
          sf org login sfdx-url -f ./SFDX_AUTH_URL.txt -a deployorg
          rm ./SFDX_AUTH_URL.txt
        
      - name: Generate delta 
        run: | 
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*' 
          git fetch --all 
          mkdir -p .sgd-output 
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output-dir .sgd-output 
          cat .sgd-output/package/package.xml  

      - name: Deploy delta 
        run: | 
          # Check if package.xml has content beyond just the version
          if grep -q "<types>" .sgd-output/package/package.xml; then
            sf project deploy preview \
              --manifest .sgd-output/package/package.xml \
              --post-destructive-changes .sgd-output/destructiveChanges/destructiveChanges.xml \
              --target-org deployorg
            
            sf project deploy start \
              --manifest .sgd-output/package/package.xml \
              --post-destructive-changes .sgd-output/destructiveChanges/destructiveChanges.xml \
              --target-org deployorg
          else
            echo "No changes to deploy in package.xml"
          fi
